import {el,escapeHTML as esc,todayISO} from './utils.js';
import {cents,dollars} from './accounting.js';
import {settingsFor,DEFAULT_SETTINGS} from './settings.js';
import {saveSettings} from './db.js';
import {MODULES,routeTitle} from './navigation.js';
import {saveVendor,postInvoice,payInvoice,postExpense,postTransfer,importStatement,bookTransactions,reconciledIds,reconciliationCheck,matchStatementRow,finishReconciliation,openingReconciliation,deleteStatement,unpaid} from './operations.js';
export function createModules({state,toast,save,go,card,table,money}){
 const d=state.data,p=settingsFor(d),user=state.user.uid,today=todayISO();
 const values=form=>Object.fromEntries([...form.elements].filter(e=>e.name).map(e=>[e.name,e.type==='checkbox'?e.checked:e.value]));
 const input=(name,label,value='',type='text',extra='')=>`<div class="field"><label for="m-${name}">${label}</label><input id="m-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
 const select=(name,label,options,value='')=>`<div class="field"><label for="m-${name}">${label}</label><select id="m-${name}" name="${name}">${options.map(([id,title])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(title)}</option>`).join('')}</select></div>`;
 const check=(name,label,value)=>`<label class="checkField"><input name="${name}" type="checkbox" ${value?'checked':''}>${label}</label>`;
 const accountOptions=(types,blank='Choose account')=>[['',blank],...d.accounts.filter(a=>a.isActive!==false && types.includes(a.type)).map(a=>[a.id,`${a.code} · ${a.name}`])];
 const vendorOptions=()=>[['','Choose vendor'],...d.vendors.map(v=>[v.id,v.name])];
 const name=id=>d.accounts.find(a=>a.id===id)?.name || '—';
 const vendor=id=>d.vendors.find(v=>v.id===id)?.name || '—';
 const none=n=>`<tr><td colspan="${n}" class="muted">No records yet.</td></tr>`;
 const form=(fields,label,action)=>{
  const f=el(`<form class="moduleForm" data-dirty><div class="grid2">${fields}</div><div class="row sectionSpace"><button class="btn primary" type="submit">${label}</button></div></form>`);
  f.onsubmit=e=>{e.preventDefault();save(f.querySelector('[type=submit]'),()=>action(values(f)),'Saved successfully.');};return f;
 };
 const amountField=()=>input('amount','Amount','','number','min="0.01" step="0.01" required');
 const reportToolbar=root=>{const b=el('<div class="headerActions row"><button class="btn" type="button">Print</button></div>');b.firstElementChild.onclick=()=>window.print();root.querySelector('.cardHeader').append(b);};
 function hub(id){const m=MODULES.find(m=>m.id===id),root=card(m.name,m.description);const grid=el('<div class="moduleGrid"></div>');for(const [route,title] of m.pages){const b=el(`<button class="moduleTile"><strong>${esc(title)}</strong><span>Open ${esc(title.toLowerCase())} →</span></button>`);b.onclick=()=>go(route);grid.append(b);}root.append(grid);return root;}
 function vendors(){const root=card('Vendors','Vendor records are used by invoices and payments.');root.append(form(input('name','Vendor name','','text','required maxlength="120"')+input('email','Email','','email')+input('notes','Notes'), 'Save vendor',v=>saveVendor(user,v)));root.append(el(table(['Vendor','Email','Notes'],d.vendors.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.email)}</td><td>${esc(v.notes)}</td></tr>`).join('') || none(3))));return root;}
 function invoices(){
  const root=card('Accounts Payable','Post vendor invoices: debit expense, credit accounts payable. Posted documents remain in the audit history.');
  const due=new Date(today+'T12:00:00');due.setDate(due.getDate()+p.dueDays);const dueDate=`${due.getFullYear()}-${String(due.getMonth()+1).padStart(2,'0')}-${String(due.getDate()).padStart(2,'0')}`;
  root.append(form(select('vendorId','Vendor',vendorOptions())+input('number','Invoice number','','text','required')+input('date','Invoice date',today,'date','required')+input('dueDate','Due date',dueDate,'date','required')+amountField()+select('expenseAccount','Expense account',accountOptions(['Expense']),p.expenseAccount)+select('payableAccount','Accounts payable account',accountOptions(['Liability']),p.payableAccount)+input('memo','Description'), 'Post invoice',v=>postInvoice(user,v)));
  if(!d.vendors.length)root.append(el('<p class="alert">Create a vendor in the Vendors tab before posting an invoice.</p>'));
  const rows=d.invoices.map(i=>`<tr><td>${esc(i.number)}</td><td>${esc(vendor(i.vendorId))}</td><td>${esc(i.date)}</td><td>${esc(i.dueDate)}</td><td>${money(i.amount)}</td><td>${money(unpaid(d,i))}</td><td>${cents(unpaid(d,i))===0?'Paid':i.dueDate<today?'Overdue':'Open'}</td><td>${cents(unpaid(d,i))>0?`<button class="btn" data-pay="${esc(i.id)}">Pay</button>`:''}</td></tr>`).join('');root.append(el(table(['Invoice','Vendor','Date','Due','Amount','Outstanding','Status','Action'],rows || none(8))));
  for(const b of root.querySelectorAll('[data-pay]'))b.onclick=()=>{state.selectedInvoice=b.dataset.pay;go('payments');};return root;
 }
 function payments(){const root=card('Invoice Payments','Pay all or part of an invoice. Payments reduce accounts payable without recording the expense twice.');
  const options=[['','Choose unpaid invoice'],...d.invoices.filter(i=>cents(unpaid(d,i))>0).map(i=>[i.id,`${i.number} · ${vendor(i.vendorId)} · ${money(unpaid(d,i))}`])];
  const selected=d.invoices.find(i=>i.id===state.selectedInvoice && cents(unpaid(d,i))>0);
  const f=form(select('invoiceId','Invoice',options,selected?.id || '')+input('date','Payment date',today,'date','required')+input('amount','Payment amount',selected?unpaid(d,selected):'','number','min="0.01" step="0.01" required')+select('paymentAccount','Payment account',accountOptions(['Asset','Liability']),p.paymentAccount)+input('reference','Payment reference'), 'Post payment',v=>payInvoice(user,v));
  f.querySelector('[name=invoiceId]').onchange=e=>{const i=d.invoices.find(i=>i.id===e.target.value);f.querySelector('[name=amount]').value=i?unpaid(d,i):'';};root.append(f);
  root.append(el(table(['Date','Invoice','Account','Amount','Reference'],d.payments.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(d.invoices.find(i=>i.id===x.invoiceId)?.number)}</td><td>${esc(name(x.paymentAccount))}</td><td>${money(x.amount)}</td><td>${esc(x.reference)}</td></tr>`).join('') || none(5))));return root;}
 function expenses(){const root=card('Daily Expenses','Record expenses paid by cash, bank transfer, debit card, or credit card. Each save posts a balanced journal entry.');
 const f=form(input('date','Expense date',today,'date','required')+input('payee','Payee','','text','required')+amountField()+select('method','Payment method',[['bank','Bank transfer'],['debit','Debit card'],['credit','Credit card'],['cash','Cash']])+select('expenseAccount','Expense account',accountOptions(['Expense']),p.expenseAccount)+select('paymentAccount','Paid from / card account',accountOptions(['Asset']),p.paymentAccount)+input('reference','Reference')+input('memo','Memo'), 'Post expense',v=>postExpense(user,v));
 f.querySelector('[name=method]').onchange=e=>{const old=f.querySelector('[name=paymentAccount]');const tmp=el(select('paymentAccount','Paid from / card account',accountOptions(e.target.value==='credit'?['Liability']:['Asset']),p.paymentAccount));old.replaceChildren(...tmp.querySelector('select').children);old.value=[...old.options].some(o=>o.value===p.paymentAccount)?p.paymentAccount:'';};root.append(f);
 root.append(el(table(['Date','Payee','Method','Expense account','Paid from','Amount'],d.expenses.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.payee)}</td><td>${esc(x.method)}</td><td>${esc(name(x.expenseAccount))}</td><td>${esc(name(x.paymentAccount))}</td><td>${money(x.amount)}</td></tr>`).join('') || none(6))));return root;}
 function transfers(){const root=card('Transfers & Card Payments','Move funds between asset accounts or pay a credit card liability. This does not create an expense.');root.append(form(input('date','Transfer date',today,'date','required')+amountField()+select('fromAccount','From bank / cash account',accountOptions(['Asset']),p.paymentAccount)+select('toAccount','To bank / credit card account',accountOptions(['Asset','Liability']))+input('reference','Reference')+input('memo','Memo'), 'Post transfer',v=>postTransfer(user,v)));root.append(el(table(['Date','Reference','Memo'],d.journalHeaders.filter(h=>h.source==='transfer').map(h=>`<tr><td>${esc(h.date)}</td><td>${esc(h.ref)}</td><td>${esc(h.memo)}</td></tr>`).join('') || none(3))));return root;}
 function statements(){const root=card('Bank & Card Statements','Import CSV statements for bank, debit-card, and credit-card accounts. Importing a statement does not post journal entries.');
 root.append(el('<p class="alert">CSV columns: <code>date,description,amount</code>. Dates: YYYY-MM-DD. For bank/debit accounts, deposits are positive and withdrawals negative. For credit cards with a credit normal balance, charges are positive and payments negative. Export CSV from your bank; PDF extraction and live bank feeds are not included.</p>'));
 const f=form(select('accountId','Statement account',accountOptions(['Asset','Liability']),p.reconcileAccount)+input('name','Statement name')+input('start','Period start',today.slice(0,7)+'-01','date','required')+input('end','Period end',today,'date','required')+input('opening','Opening statement balance','0','number','step="0.01" required')+input('closing','Closing statement balance','','number','step="0.01" required')+input('file','Statement CSV','','file','accept=".csv,text/csv" required'), 'Import statement',async v=>{
 const file=f.querySelector('[type=file]').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>1000000)throw Error('CSV must be under 1 MB.');await importStatement(user,{...v,csv:await file.text()});});root.append(f);
 root.append(el(table(['Statement','Account','Period','Closing balance','Status','Actions'],d.statements.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(name(s.accountId))}</td><td>${esc(s.start)} – ${esc(s.end)}</td><td>${money(s.closing)}</td><td>${esc(s.status)}</td><td><button class="btn" data-reconcile="${s.id}">Review</button> ${s.status==='open'?`<button class="btn" data-remove="${s.id}">Remove</button>`:''}</td></tr>`).join('') || none(6))));
 for(const b of root.querySelectorAll('[data-reconcile]'))b.onclick=()=>{state.selectedStatement=b.dataset.reconcile;go('reconcile');};for(const b of root.querySelectorAll('[data-remove]'))b.onclick=()=>{if(confirm('Remove this open statement and its matches? Journal entries will remain.'))save(b,()=>deleteStatement(user,b.dataset.remove),'Statement removed.');};return root;}
 function reconcile(){const root=card('Reconciliation','Match statement activity to posted books, review outstanding items, and finish only when the difference is zero.');
 const selectBox=el(select('statementId','Statement',[['','Choose statement'],...d.statements.map(s=>[s.id,`${name(s.accountId)} · ${s.end} · ${s.status}`])],state.selectedStatement || ''));selectBox.querySelector('select').onchange=e=>{state.selectedStatement=e.target.value;go('reconcile');};root.append(selectBox);
 const s=d.statements.find(s=>s.id===state.selectedStatement);
 if(s){const c=reconciliationCheck(d,s);root.append(el(`<div class="stats"><div><span class="small">Book balance</span><div class="bigNumber">${money(c.bookTotal)}</div></div><div><span class="small">Outstanding activity</span><div class="bigNumber">${money(c.outstandingTotal)}</div></div><div><span class="small">Statement balance</span><div class="bigNumber">${money(s.closing)}</div></div><div><span class="small">Difference</span><div class="bigNumber">${money(c.difference)}</div></div></div>`));
 if(s.status==='reconciled')root.append(el('<p class="badge good">Reconciliation completed. Cleared transactions are preserved.</p>'));
 else{
 if(!c.openingMatches)root.append(el('<p class="alert">The opening statement balance does not match the previous reconciliation. Set up the opening reconciliation below, or complete earlier statements first.</p>'));
 const used=reconciledIds(d,s.accountId);
 root.append(el(table(['Date','Description','Signed amount','Matched book transaction'],s.rows.map(row=>`<tr><td>${esc(row.date)}</td><td>${esc(row.description)}</td><td>${money(row.amount)}</td><td><select aria-label="Match ${esc(row.description)}" data-match="${row.id}"><option value="">Unmatched</option>${c.books.filter(b=>cents(b.amount)===cents(row.amount) && !used.has(b.id) && !d.statements.some(x=>x.rows.some(r=>r.id!==row.id && r.bookLineId===b.id))).map(b=>`<option value="${b.id}" ${row.bookLineId===b.id?'selected':''}>${esc(b.date+' · '+b.memo+' · '+money(b.amount))}</option>`).join('')}</select></td></tr>`).join(''))));
 for(const x of root.querySelectorAll('[data-match]'))x.onchange=()=>save(x,()=>matchStatementRow(user,s.id,x.dataset.match,x.value),'Match saved.');
 const finish=el('<button class="btn primary">Complete reconciliation</button>');finish.disabled=!c.openingMatches || !c.allMatched || cents(c.difference)!==0;finish.onclick=()=>save(finish,()=>finishReconciliation(user,s.id),'Reconciliation completed.');root.append(finish);
 }
 root.append(el('<h3>Outstanding book transactions</h3>'));root.append(el(table(['Date','Memo','Signed amount'],c.outstanding.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.memo)}</td><td>${money(x.amount)}</td></tr>`).join('') || none(3))));
 }
 const details=el('<details class="sectionSpace"><summary>First-time setup: opening reconciliation</summary><p class="muted">Use only when every book transaction through this date has already cleared. The entered balance must equal the book balance; all those transactions will be marked reconciled. Otherwise, reconcile from the start of your books.</p></details>');
 details.append(form(select('accountId','Opening account',accountOptions(['Asset','Liability']),p.reconcileAccount)+input('end','Previously reconciled through','','date','required')+input('closing','Confirmed opening balance','','number','step="0.01" required'), 'Save opening reconciliation',v=>{if(!confirm('Confirm all transactions through this date have cleared? This locks them as reconciled.'))throw Error('Opening reconciliation cancelled.');return openingReconciliation(user,v);}));root.append(details);
 root.append(el('<h3>Completed reconciliations</h3>'));root.append(el(table(['Account','Through','Closing balance','Kind'],d.reconciliations.map(r=>`<tr><td>${esc(name(r.accountId))}</td><td>${esc(r.end)}</td><td>${money(r.closing)}</td><td>${esc(r.kind)}</td></tr>`).join('') || none(4))));return root;}
 function review(){const root=card('Review Journal','Posted entries are permanent. Expand an entry to see its debit and credit lines.');reportToolbar(root);
 const search=el(input('journalSearch','Search journal','','search'));root.append(search);const output=el('<div></div>');root.append(output);let page=0;
 const draw=()=>{const query=search.querySelector('input').value.toLowerCase(),rows=d.journalHeaders.filter(h=>`${h.date} ${h.ref} ${h.memo} ${h.source || 'journal'}`.toLowerCase().includes(query)).sort((a,b)=>b.date.localeCompare(a.date) || b.createdAt-a.createdAt);const max=Math.max(1,Math.ceil(rows.length/p.pageSize));page=Math.min(page,max-1);output.innerHTML=table(['Date','Reference','Source','Details','Amount'],rows.slice(page*p.pageSize,(page+1)*p.pageSize).map(h=>{const ls=d.journalLines.filter(l=>l.headerId===h.id);return `<tr><td>${esc(h.date)}</td><td>${esc(h.ref)}</td><td>${esc(h.source || 'journal')}</td><td><details><summary>${esc(h.memo || 'Entry details')}</summary>${ls.map(l=>`<div>${esc(name(l.accountId))}: debit ${money(l.debit)}, credit ${money(l.credit)}</div>`).join('')}</details></td><td>${money(dollars(ls.reduce((n,l)=>n+cents(l.debit),0)))}</td></tr>`;}).join('') || none(5))+`<div class="row"><button class="btn" data-prev ${page===0?'disabled':''}>Previous</button><span>Page ${page+1} of ${max} · ${rows.length} entries</span><button class="btn" data-next ${page===max-1?'disabled':''}>Next</button></div>`;output.querySelector('[data-prev]').onclick=()=>{page--;draw();};output.querySelector('[data-next]').onclick=()=>{page++;draw();};};search.querySelector('input').oninput=()=>{page=0;draw();};draw();return root;}
 function aging(){const root=card('AP Aging','Outstanding posted invoices as of the selected date, reduced only by payments made on or before that date.');reportToolbar(root);const f=el(`<form class="row filters">${input('agingDate','As of',today,'date','required')}<button class="btn">Apply</button></form>`),out=el('<div></div>');root.append(f,out);
 const draw=()=>{const end=f.querySelector('input').value;let total=0;const rows=d.invoices.filter(i=>i.date<=end).map(i=>{const due=cents(i.amount)-d.payments.filter(x=>x.invoiceId===i.id && x.date<=end).reduce((n,x)=>n+cents(x.amount),0);if(!due)return '';total+=due;const days=Math.max(0,Math.floor((Date.parse(end+'T12:00:00Z')-Date.parse(i.dueDate+'T12:00:00Z'))/86400000));return `<tr><td>${esc(vendor(i.vendorId))}</td><td>${esc(i.number)}</td><td>${esc(i.dueDate)}</td><td>${days===0?'Current':days<=30?'1–30':days<=60?'31–60':days<=90?'61–90':'90+'}</td><td>${money(dollars(due))}</td></tr>`;}).join('');out.innerHTML=table(['Vendor','Invoice','Due','Days overdue','Outstanding'],(rows || none(5))+`<tr class="total"><td colspan="4">Total outstanding</td><td>${money(dollars(total))}</td></tr>`);};f.onsubmit=e=>{e.preventDefault();draw();};draw();return root;}
 function settings(){const root=card('Master Settings','Saved defaults apply to these books. Changes do not rewrite historical transactions.');
 const f=el('<form class="settingsForm" data-dirty></form>');
 const section=(title,fields)=>f.append(el(`<fieldset><legend>${title}</legend><div class="grid2">${fields}</div></fieldset>`));
 const periods=[['all','All history'],['month','Current month'],['year','Calendar year'],['fiscal','Fiscal year']];
 section('General & dashboard',input('bookName','Book name',p.bookName,'text','required')+select('density','Display density',[['compact','Compact'],['comfortable','Comfortable']],p.density)+input('dashboardCount','Recent entries on dashboard',p.dashboardCount,'number','min="1" max="50" required')+input('fiscalMonth','Fiscal year starting month (1–12)',p.fiscalMonth,'number','min="1" max="12" required'));
 section('General Ledger',input('closedThrough','Close posting through date',p.closedThrough,'date')+input('referencePrefix','Default journal reference prefix',p.referencePrefix)+input('pageSize','Journal review entries per page',p.pageSize,'number','min="10" max="100" required')+check('requireMemo','Require a journal memo',p.requireMemo)+check('showInactive','Show disabled accounts by default',p.showInactive));
 section('Reports',select('isPeriod','Income Statement default period',periods,p.isPeriod)+select('ledgerPeriod','General Ledger default period',periods,p.ledgerPeriod)+check('trialZero','Trial Balance: show zero balances',p.trialZero)+check('bsZero','Balance Sheet: show zero balances',p.bsZero)+check('isZero','Income Statement: show zero balances',p.isZero)+check('ledgerEmpty','General Ledger: show accounts without period activity',p.ledgerEmpty)+check('printLandscape','Print reports in landscape',p.printLandscape));
 section('Expenses & accounts payable',select('expenseAccount','Default expense account',accountOptions(['Expense'],'No default'),p.expenseAccount)+select('paymentAccount','Default bank / payment account',accountOptions(['Asset'],'No default'),p.paymentAccount)+select('payableAccount','Default accounts payable account',accountOptions(['Liability'],'No default'),p.payableAccount)+input('dueDays','Invoice payment terms (days)',p.dueDays,'number','min="0" max="365" required'));
 section('Statements & reconciliation',select('reconcileAccount','Default statement / reconciliation account',accountOptions(['Asset','Liability'],'No default'),p.reconcileAccount));
 f.append(el('<div class="row sectionSpace"><button class="btn primary" type="submit">Save settings</button><button class="btn" type="button" data-reset>Restore default settings</button><button class="btn" type="button" data-backups>Backups & storage</button></div>'));
 f.onsubmit=e=>{e.preventDefault();save(f.querySelector('[type=submit]'),()=>saveSettings(user,values(f)),'Settings saved.');};
 f.querySelector('[data-reset]').onclick=e=>{if(confirm('Restore default preferences? Your accounting records will remain.'))save(e.target,()=>saveSettings(user,DEFAULT_SETTINGS),'Default settings restored.');};f.querySelector('[data-backups]').onclick=()=>document.getElementById('btnBackups').click();root.append(f);return root;}
 return {gl:()=>hub('gl'),reports:()=>hub('reports'),expenseHub:()=>hub('expenseHub'),settings,vendors,invoices,payments,expenses,transfers,statements,reconcile,review,aging};
}
