import {el,escapeHTML as esc,todayISO} from './utils.js';
import {cents,dollars} from './accounting.js';
import {exportData} from './db.js';
import {transactionTemplate} from './csv-ui.js';
import {importStatement,parseStatementCSV,reconciledIds,reconciliationCheck,matchStatementRow,finishReconciliation,openingReconciliation,postReconciliationAdjustment} from './operations.js';
export function reconciliationUI({state,toast,save,go,card,table,money,form,input,select,accountOptions,name,p}){
 const d=state.data,user=state.user.uid,today=todayISO(),root=card('Reconciliation','Compare imported bank or card activity with posted books. Match the cleared items and review what remains on either side.');
 const s=d.statements.find(s=>s.id===state.selectedStatement);
 const actions=el('<div class="headerActions row"><button class="btn" data-bank-import>Import CSV</button><button class="btn" data-bank-template>Download Template</button></div>');root.querySelector('.cardHeader').append(actions);
 actions.querySelector('[data-bank-template]').onclick=transactionTemplate;
 const upload=el(`<details class="reconcileImport" ${d.statements.length?'':'open'}><summary>Import a bank or card statement</summary><p class="muted">Template columns: date,description,amount. Use YYYY-MM-DD. Bank deposits are positive and withdrawals negative; credit-card charges are positive and payments negative. Enter balances from the statement. Importing creates a comparison, not journal entries.</p></details>`);
 const f=form(select('accountId','Import account',accountOptions(['Asset','Liability']),s?.accountId || p.reconcileAccount)+input('name','Statement name')+input('start','Period start',today.slice(0,7)+'-01','date','required')+input('end','Period end',today,'date','required')+input('opening','Opening statement balance','0','number','step="0.01" required')+input('closing','Closing statement balance','','number','step="0.01" required')+input('file','Bank transactions CSV','','file','accept=".csv,text/csv" required'),'Import bank CSV',async v=>{
 const file=f.querySelector('[type=file]').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>1000000)throw Error('CSV must be under 1 MB.');
 await importStatement(user,{...v,csv:await file.text()});const data=(await exportData(user)).data;state.selectedStatement=data.statements.find(x=>x.accountId===v.accountId && x.start===v.start && x.end===v.end)?.id;
 });
 const hint=el('<p class="small" role="status"></p>');f.append(hint);f.querySelector('[type=file]').onchange=async e=>{try{const file=e.target.files[0];if(!file){hint.textContent='';return;}if(file.size>1000000)throw Error('CSV must be under 1 MB.');const rows=parseStatementCSV(await file.text());hint.textContent=`${rows.length} bank transactions · signed total ${money(dollars(rows.reduce((n,r)=>n+cents(r.amount),0)))}. Fill in the statement details, then import.`;}catch(e){hint.textContent=e.message;}};
 const sample=el('<button class="btn" type="button">Download Template</button>');sample.onclick=transactionTemplate;f.querySelector('.row').append(sample);upload.append(f);root.append(upload);
 actions.querySelector('[data-bank-import]').onclick=()=>{upload.open=true;upload.scrollIntoView({block:'start',behavior:'smooth'});f.querySelector('select').focus();};
 const chooser=el(select('statementId','Statement to reconcile',[['','Choose statement'],...d.statements.map(x=>[x.id,`${name(x.accountId)} · ${x.end} · ${x.status}`])],state.selectedStatement || ''));
 chooser.querySelector('select').onchange=e=>{state.selectedStatement=e.target.value;go('reconcile');};root.append(chooser);
 if(s){
 const c=reconciliationCheck(d,s),closed=s.status==='reconciled';
 root.append(el(`<div class="stats"><div><span class="small">Book balance</span><div class="bigNumber">${money(c.bookTotal)}</div></div><div><span class="small">Outstanding book activity</span><div class="bigNumber">${money(c.outstandingTotal)}</div></div><div><span class="small">Statement balance</span><div class="bigNumber">${money(s.closing)}</div></div><div><span class="small">Difference</span><div class="bigNumber">${money(c.difference)}</div></div></div>`));
 if(closed)root.append(el('<p class="badge good">Reconciliation completed. Cleared transactions are preserved.</p>'));
 else if(!c.openingMatches)root.append(el('<p class="alert">The opening statement balance must match the previous completed reconciliation. For first-time setup, use the opening reconciliation section below.</p>'));
 const controls=el(`<div class="row compareToolbar"><label class="checkField"><input type="checkbox" data-unmatched>Show unmatched only</label><span class="small">${closed?'Completed comparison':'Select one item on each side, then match the pair. Amounts must agree.'}</span><div class="spacer"></div><button class="btn" type="button" data-adjust ${closed?'disabled':''}>Add adjustment</button><button class="btn primary" type="button" data-pair disabled>Match selected pair</button></div>`);root.append(controls);
 const currentMatches=new Set(s.rows.filter(r=>r.bookLineId).map(r=>r.bookLineId)),prior=reconciledIds(d,s.accountId);currentMatches.forEach(id=>prior.delete(id));
 const bookRows=c.books.filter(b=>!prior.has(b.id));let selectedBank='',selectedBook='';
 const compare=el('<div class="reconcileCompare"></div>');
 const bankPanel=el(`<section class="comparePanel"><h3>Imported bank transactions</h3><p class="small">${s.rows.filter(r=>!r.bookLineId).length} unmatched · ${s.rows.length} total</p></section>`);
 bankPanel.append(el(table(['Clear','Date / description','Amount','Status'],s.rows.map(row=>`<tr data-bank-row="${row.id}" data-cleared="${!!row.bookLineId}"><td><input type="checkbox" aria-label="Select bank transaction ${esc(row.description)}" data-bank="${row.id}" ${row.bookLineId?'checked disabled':closed?'disabled':''}></td><td><span class="small">${esc(row.date)}</span><br>${esc(row.description)}</td><td class="right">${money(row.amount)}</td><td>${row.bookLineId?`<span class="badge good">Cleared</span>${closed?'':`<button class="btn" data-unmatch="${row.id}">Unmatch</button>`}`:'Unmatched'}</td></tr>`).join(''))));
 const bookPanel=el(`<section class="comparePanel"><h3>System transactions</h3><p class="small">${c.outstanding.length} outstanding · previously reconciled items excluded</p></section>`);
 bookPanel.append(el(table(['Clear','Date / memo','Amount','Status'],bookRows.map(b=>{
 const elsewhere=d.statements.some(x=>x.id!==s.id && x.rows.some(r=>r.bookLineId===b.id));
 return `<tr data-book-row="${b.id}" data-cleared="${currentMatches.has(b.id)}"><td><input type="checkbox" aria-label="Select system transaction ${esc(b.memo || b.date)}" data-book="${b.id}" ${currentMatches.has(b.id)?'checked disabled':closed || elsewhere?'disabled':''}></td><td><span class="small">${esc(b.date)}</span><br>${esc(b.memo || 'Journal entry')}</td><td class="right">${money(b.amount)}</td><td>${currentMatches.has(b.id)?'<span class="badge good">Cleared</span>':elsewhere?'Matched to another statement':'Outstanding'}</td></tr>`;
 }).join('') || '<tr><td colspan="4">No book transactions available. Add missing activity using an adjustment or journal entry.</td></tr>')));
 compare.append(bankPanel,bookPanel);root.append(compare);
 const selected=el('<p class="small" role="status"></p>');root.append(selected);
 const update=()=>{const left=s.rows.find(r=>r.id===selectedBank),right=bookRows.find(r=>r.id===selectedBook);controls.querySelector('[data-pair]').disabled=closed || !left || !right || cents(left.amount)!==cents(right.amount);selected.textContent=left && right?(cents(left.amount)===cents(right.amount)?'Selected amounts match.':'Selected amounts differ. Choose a matching transaction or post an adjustment.'):'';};
 for(const box of compare.querySelectorAll('[data-bank]:not(:disabled)'))box.onchange=()=>{selectedBank=box.checked?box.dataset.bank:'';for(const other of compare.querySelectorAll('[data-bank]:not(:disabled)'))if(other!==box)other.checked=false;update();};
 for(const box of compare.querySelectorAll('[data-book]:not(:disabled)'))box.onchange=()=>{selectedBook=box.checked?box.dataset.book:'';for(const other of compare.querySelectorAll('[data-book]:not(:disabled)'))if(other!==box)other.checked=false;update();};
 controls.querySelector('[data-unmatched]').onchange=e=>{for(const row of compare.querySelectorAll('tr[data-cleared]'))row.hidden=e.target.checked && row.dataset.cleared==='true';};
 controls.querySelector('[data-pair]').onclick=e=>save(e.target,()=>matchStatementRow(user,s.id,selectedBank,selectedBook),'Match saved.');
 for(const button of compare.querySelectorAll('[data-unmatch]'))button.onclick=()=>save(button,()=>matchStatementRow(user,s.id,button.dataset.unmatch,''),'Match removed.');
 const adjust=el('<details class="sectionSpace adjustmentPanel"><summary>Post a reconciliation adjustment</summary><p class="muted">Enter the signed change to this bank/card balance and select the offset account. A balanced journal entry is posted. Match it afterward; no difference is silently written off.</p></details>');
 if(!closed){
 const adjustment=form(input('date','Adjustment date',s.end,'date','required')+input('amount','Signed balance change','','number','step="0.01" required')+select('offsetAccount','Offset account',accountOptions(['Asset','Liability','Equity','Revenue','Expense']),p.expenseAccount)+input('reference','Adjustment reference')+input('memo','Adjustment memo','','text','required'),'Post adjustment',v=>postReconciliationAdjustment(user,{...v,accountId:s.accountId}));adjust.append(adjustment);root.append(adjust);
 controls.querySelector('[data-adjust]').onclick=()=>{const bankRow=s.rows.find(r=>r.id===selectedBank);adjust.open=true;if(bankRow){adjustment.querySelector('[name=date]').value=bankRow.date;adjustment.querySelector('[name=amount]').value=bankRow.amount;adjustment.querySelector('[name=memo]').value=bankRow.description;}adjust.scrollIntoView({block:'start',behavior:'smooth'});adjustment.querySelector('[name=offsetAccount]').focus();};
 const finish=el('<button class="btn primary" type="button">Complete reconciliation</button>');finish.disabled=!c.openingMatches || !c.allMatched || cents(c.difference)!==0;finish.onclick=()=>save(finish,()=>finishReconciliation(user,s.id),'Reconciliation completed.');root.append(finish);
 }
 }
 const baseline=el('<details class="sectionSpace"><summary>First-time setup: opening reconciliation</summary><p class="muted">Use only when every book transaction through this date has already cleared. The entered balance must equal the books; all those transactions will be marked reconciled. Otherwise, reconcile from the start of your books.</p></details>');
 baseline.append(form(select('accountId','Opening account',accountOptions(['Asset','Liability']),p.reconcileAccount)+input('end','Previously reconciled through','','date','required')+input('closing','Confirmed opening balance','','number','step="0.01" required'),'Save opening reconciliation',v=>{if(!confirm('Confirm all transactions through this date have cleared?'))throw Error('Opening reconciliation cancelled.');return openingReconciliation(user,v);}));root.append(baseline);
 root.append(el('<h3>Completed reconciliations</h3>'));root.append(el(table(['Account','Through','Closing balance','Kind'],d.reconciliations.map(r=>`<tr><td>${esc(name(r.accountId))}</td><td>${esc(r.end)}</td><td>${money(r.closing)}</td><td>${esc(r.kind)}</td></tr>`).join('') || '<tr><td colspan="4">No completed reconciliations.</td></tr>')));return root;
}
